server:
  port: 8080

spring:
  application:
    name: poke-companion-api
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:mem:pokecompanion-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:data/init.sql